version: '3'

services:
  app:
    image: douglasnobre65/hortobackend:v2.5
    build: .
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: 'npm run dev'