version: '3'

services:
  app:
    image: hortoflorestalbackend-app:latest 
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: 'npm run dev'