name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets
        run: |
          echo "Host: ${{ secrets.HOST }}"
          echo "Username: ${{ secrets.USERNAME }}"
          echo "SSH Private Key: ${{ secrets.SSH_PRIVATE_KEY }}"
          # Você também pode usar "echo" para imprimir o conteúdo da chave privada, mas tenha cuidado ao fazer isso,
          # pois pode expor informações confidenciais no log.
          # echo "${{ secrets.SSH_PRIVATE_KEY }}"
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd appnest
            git pull origin master
            git status
            npm i
            npm run build
            npm run start:prod
