name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: NPM Install
        run: npm install

      - name: Setup Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 20
          which npm
          
      - name: Set NVM and npm config
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          export NPM_CONFIG_PREFIX=~/.npm-global

      - name: Install PM2
        run: npm install pm2@latest -g

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/hortoflorestal
            cd appnest
            ls -a
            git pull
            npm install pm2@latest -g
            npm run build
            pm2 restart all
            

