name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          # Especifique o diretório de instalação do Node.js
          node-path: './node_modules'

      - name: NPM Install
        run: npm install

      - name: Add npm to PATH
        run: export PATH="${{ github.workspace }}/node_modules/.bin:$PATH"

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/hortoflorestal
            ls -a
            cd appnest
            git pull
            npm i
            npm run build
            npm run start:prod
