name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: NPM Install
        run: npm ci

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/hortoflorestal
            ls -a
            cd appnest
            git pull
            npm i
            npm run build
            npm run start:prod
