name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: NPM Install
        run: /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm install

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/hortoflorestal
            ls -a
            cd appnest
            git pull
            /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm install
            /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm run build
            /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm run start:prod
